// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package pkg

import (
	"Go-000/Week04/api"
	"Go-000/Week04/internal/server1/biz"
	"Go-000/Week04/internal/server1/data"
	"Go-000/Week04/internal/server1/service"
)

// Injectors from wire.go:

func InitService() api.GetTestDataServiceServer {
	testDataRepo := data.NewTestDataRepo()
	testDataUsercase := biz.NewTestDataUsercase(testDataRepo)
	getTestDataServiceServer := service.NewGetTestDataService(testDataUsercase)
	return getTestDataServiceServer
}
